config/routes.rb
Rails.application.routes.draw do
  root "billboards#index"

  resources :billboards do
    resources :songs
  end

  resources :artists do
    resources :songs
  end

  resources :songs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist, required: true
  belongs_to :billboard, optional: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :update, :edit, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end
  
  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :genre)
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy]

  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboards_path
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
  def set_billboard
    @billboard = Billboard.find(params[:id])
  end

  def billboard_params
    params.require(:billboard).permit(:name)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :update, :edit, :destroy]

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to artist_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to billboard_path(@song.billboard_id)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private
  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :genre)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<p>Hey! You've reached the EDIT page for Artists!<p>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.submit %>
<% end %>

<button><%= link_to 'Back', artists_path %></button>
<button><%= link_to 'Edit', edit_artist_path(artist) %></button>

app/views/artists/index.html.erb
<button class="ui left floated button"><%= link_to 'Back to Billboards', billboards_path %></button>
<br>
<h1>Artists</h1>

<div class="container">
  <% @artists.each do |artist| %>
  <div class="ui card" >
    <div class="content">
      <h2><%= artist.name %></h2>
    </div>
    <div class="extra content">
      <button class="ui primary left floated button"><%= link_to 'Show', artist_path(artist) %></button>
      <button class="ui right floated button"><%= link_to 'Delete', artist, method: :delete %></button>
    </div>
  </div>
  <% end %>
</div>

app/views/artists/new.html.erb
<p>Welcome to the NEW page for artists!<p>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.submit %>
<% end %>

<%= link_to 'Return to the main page without submitting', artists_path %>

app/views/artists/show.html.erb
<div class="ui">
  <div class="image">
    <img src="https://robohash.org/<%= @artist.id %>?bgset=bg1">
  </div>
  <div class="content">
    <p class="header"><%= @artist.name %></p>
  </div>
  <div class="extra content">
    <p>
      <i class="music icon"></i>
      Genre: <%= @artist.genre %>
    </p>
  </div>
</div>
<%= link_to 'Back', artists_path %>
<%= link_to 'Edit', edit_artist_path(@artist.id) %>

app/views/billboards/edit.html.erb
<p>Hey! You've reached the EDIT page!<p>

<%= form_for @billboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

<%= link_to 'Back', billboards_path %>

app/views/billboards/index.html.erb
<h1>Find all your billboards here!</h1>
<hr>

<% @billboards.each do |billboard| %>
  <div class="ui card">
  <h2>Top <%= billboard.name %> Billboard</h2>
  <button class="ui button"><%= link_to 'Show', billboard_path(billboard) %></button>
  <button class="ui button"><%= link_to 'Edit', edit_billboard_path(billboard) %></button>
  <button class="ui button"><%= link_to 'Delete', billboard, method: :delete %></button>
  </div>
<% end %>

<hr>
<h3>Don't see the one you want?<%= link_to ' Add it!', new_billboard_path %><h3>
<h3>Want to see all the <%= link_to 'artists', artists_path %>?</h3>
<h3>Want to see all the <%= link_to 'songs', songs_path %>?</h3>

app/views/billboards/new.html.erb
<p>Welcome to the NEW page!<p>

<form class="ui form">
<%= form_for @billboard do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <button class="ui button"><%= f.submit %></button>
<% end %>
</form>
<br>
<%= link_to 'Return to the main page without submitting', billboards_path %>

app/views/billboards/show.html.erb
<h1><%= @billboard.name %></h1>
<hr>
  <h2>Songs</h2>
  <ol>
    <% @billboard.songs.each do |song| %>
      <li><%= song.title %> <%= song.artist.name %></li>
      <div>
        <%= link_to 'Edit', edit_billboard_song_path([song.billboard, song.id]) %>
      </div>
    <% end %>
  </ol>
<hr>
<%= link_to 'Back', billboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Billboards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/edit.html.erb
<p>Hey! You've reached the EDIT page!<p>

<%= form_for @song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :artist_id %>
  <%= f.text_field :artist_id %>

  <%= f.submit %>
<% end %>

<%= link_to 'Back', billboard_path(@song.billboard_id) %>

app/views/songs/index.html.erb
<button class="ui left floated button"><%= link_to 'Back to Billboards', billboards_path %></button>
<br>
<h1>Songs</h1>
<table class="ui celled table">
  <thead>
    <tr>
      <th>Song Title</th>
      <th>Artist</th>
      <th>Genre</th>
      <th>Billboard Reference</th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song|%>
      <tr>
        <td><%= song.title  %></td>
        <td><%= song.artist.name  %></td>
        <td><%= song.artist.genre  %></td>
        <td>
          <% if song.billboard_id != 6 %>
            <%= song.billboard.name %>
          <% else %>
            <%= "" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>